# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
linkedin: https://www.linkedin.com/in/ariagno
github:  http://github.com/theguywhocodes
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Ariagno Blog
email: chris@ariagno.com
description: >- # this means to ignore newlines until "baseurl:"
    Hello! My name is Chris Ariagno, I'm a Student at The University of Kansas.
    This blog is meant to show off some of the cool stuff I do at Google this summer,
    and some of the lessons I learn in programming. Stay posted!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://ariagno-step-2020.appspot.com" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: ariagno
github_username:  theguywhocodes

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
